name: Check links
on:
  workflow_call:
    inputs:
        artifact-name:
          description: 'Name of the build artifact'
          default: 'build-20.x'
          required: false
          type: string

jobs:
    link-checker:
        permissions: {}
        runs-on: ubuntu-latest
        steps:
          - uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
            with:
              merge-multiple: true
              name: ${{ inputs.artifact-name }}
              path: out
    
          - name: Link Checker
            id: lychee
            uses: lycheeverse/lychee-action@1d97d84f0bc547f7b25f4c2170d87d810dc2fb2c # v2.4.0
            with:
              fail: true
              failIfEmpty: true
              args: --base out/ --verbose --no-progress --exclude 'images\.ctfassets\.net' './**/*.html' 
