name: Check links
on:
  workflow_call:
    inputs:
        artifact-name:
          description: 'Name of the build artifact'
          default: 'build-20.x'
          required: false
          type: string

jobs:
    link-checker:
        permissions: {}
        runs-on: ubuntu-latest
        steps:
          - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
            with:
              merge-multiple: true
              name: ${{ inputs.artifact-name }}
              path: out
    
          - name: Link Checker
            id: lychee
            uses: lycheeverse/lychee-action@5c4ee84814c983aa7164eaee476f014e53ff3963 # v2.5.0
            with:
              fail: true
              failIfEmpty: true
              args: --base out/ --verbose --no-progress --exclude 'videos\.ctfassets\.net' --exclude 'images\.ctfassets\.net' './**/*.html' 
